spring:
  mail:
    password: fqjqoigawdgqvlhi
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 4e7309fac62335e67a366bca8d7cae2a
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname